### ISSUE TITLE
fallback ne voit pas les instances multiples

### ISSUE THREAD

**Issue by nicolasVr** [YunoHost-Apps/fallback_ynh#15]
Bonjour,
J'ai 2 serveurs sous Yunohost dont un en secours avec fallback.
Sur le serveur principal j'ai deux instances de Nextcloud, or en regardant les sauvegardes que fait fallback, je suis à peu près sûr qu'il n'en sauvegarde qu'une, ce qui est bien embêtant.
En fait, dans le répertoire /home/fallback/updated_backup j'ai bien des sauvegardes des 2 instances à une date qui correspond à un test que j'ai fait du système de fallback (le 31 janvier).
En revanche dans /home/fallback/backup j'ai seulement une des 2 instances à la date de ce jour.
N'hésitez pas à me demander si vous avez besoin d'autres infos.

**Comment by maniackcrudelis** [comment]
Hi nicolasVr

not sure that the hook is working. So maybe the list of apps is not up to date.
Could you have a look to the list, `/home/yunohost.app/fallback/app_list` ?

**Comment by nicolasVr** [comment]
Hi,
I have no app_list file in this directory but I get it in the /home/fallback/backup directory and it only lists 1 nextcloud instance

**Comment by maniackcrudelis** [comment]
You're really supposed to have this file in `/home/yunohost.app/` https://github.com/YunoHost-Apps/fallback_ynh/blob/master/scripts/install#L329, but you should find the real file at `/opt/yunohost/fallback/send_process/app_list`.
If you have only one nextcloud instance, that's probably that the hook isn't working. This feature was implemented into this app before it was into the core of YunoHost.

**Comment by maniackcrudelis** [comment]
Just tried, it seems to work correctly.
