### ISSUE TITLE
feature request : fallback automatique en cas de panne du serveur

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/fallback_ynh#4]
Ça serait pas mal si le fallback pouvait se lancer en cas de panne du serveur, avec un délai configurable. Par exemple, si le serveur principal ne répond pas pendant 12h.
Par contre, il faut gérer le cas où le serveur principal se reconnecte pendant que le serveur secondaire est en route.
Ça me parait assez facile à gérer avec un vpn : pas de dns à gérer, et si le serveur secondaire se connecte au vpn, le principal ne peut plus.

**Comment by maniackcrudelis** [comment]
https://github.com/maniackcrudelis/Fallback-server/commit/3f9b2c19a1f337508bbbc2db55068b7a8542f940

Ça devrait correspondre à tes attentes
Concernant le changement d'ip dans le DNS, il y a possibilité d'exécuter un script, mais difficile de proposer quoi que ce soit d'universel, tant différentes configurations peuvent se présenter.
En tout cas, le script déjà fourni fonctionne pour OVH, le cas échéant.

Cette version 0.5 (et ses corrections) est intégré à la dernière version de ce package.

**Comment by tomdereub** [comment]
Je comprend pas grand chose au code, mais ça a l'air de correspondre.
Pour les DNS, vu que j'utilise un VPN je pense que je n'aurais rien à configurer. Par contre ça vaudrait le coup de pouvoir tester le serveur principal sur l'IP du VPN et sur l'IP de la maison, au cas où le problème vienne du VPN (ça arrive).
Mais bon, ça commence à faire pas mal de cas différents à gérer...

**Comment by maniackcrudelis** [comment]
Oui désolé je t'ai linké le commit, mais ce qu'il faut voir surtout c'est le nom du commit: "Auto deploy"

J'ai pas écrit de doc par contre, car c'est globalement pris en charge lors de l'install.
Mais pour un upgrade, il faudra le faire manuellement.
C'est juste le cron `deploy_process/auto_deploy_fallback.cron` et le fichier de config `deploy_process/auto_check.conf`

J'ai pas compris ton histoire d'IP du VPN. Je n'utilise pas de VPN aussi, c'est peut-être pour ça.

**Comment by tomdereub** [comment]
En gros mon serveur se connecte à mon VPN via un tunnel sécurisé. Donc sa porte de sortie sur le net est l'IP du VPN, c'est celle que je rentre dans mes DNS.
Si le serveur tombe et que le fallback se lance, le serveur secondaire va se connecter au VPN automatiquement, donc il aura la même IP que le serveur principal, donc rien à changer au niveau des DNS.

**Comment by maniackcrudelis** [comment]
OK, je comprend.
Là, le serveur principal défini son IP à tester à partir de son IP publique. J'imagine donc que ça va être le VPN dans ton cas.
Mais tu peux aussi lui indiquer une IP arbitraire à transmettre au fallback, via l'option [overwrite_ip](https://github.com/maniackcrudelis/Fallback-server/blob/master/send_process/config.conf#L16).
Par contre, tester l'IP du VPN en plus ne te permettra pas de régler quoi que ce soit, si ton VPN tombe alors que tes 2 serveurs s'y connectent, t'auras pas de connection quoi qu'il en soit.

A mon avis, dans ton cas ton fallback ne devrait pas être derrière le même VPN.
Ou alors avoir la possibilité de s'en passer si nécessaire.

**Comment by tomdereub** [comment]
Au contraire, le VPN est une aide dans mon cas pour gérer les DNS, par contre j'accepte d'avoir une interruption si le VPN tombe (ce qui est très rare, et n'a jusque là jamais duré longtemps). Voici en gros comment je vois les choses dans mon cas : 
- le fallback teste l'IP du VPN régulièrement, pour voir si le serveur principal répond
- si le serveur principal ne répond pas pendant x temps, le secondaire teste l'IP directe (chez moi). Deux cas : 
1. l'IP directe répond, ça veut dire que le problème vient du VPN, le serveur secondaire envoie une alerte mail mais ne déploie pas le fallback. On attend que le VPN soit remis en route, et ça ne dépend pas de moi, mais de mon fournisseur. Pendant ce temps-là, le serveur n'est pas accessible.
2. l'IP directe ne répond pas pendant y temps, et l'IP du VPN ne répond toujours pas, le problème vient bien du serveur principal. -» déploiement du fallback et on envoie une alerte mail. Et du coup il n'y a pas de DNS à gérer, le serveur secondaire se connecte au VPN.
Et le transfert dans l'autre sens se fait manuellement, quand je suis rentré à la maison.

**Comment by maniackcrudelis** [comment]
Hum ok, je vois.
Et si tu testes directement l'IP du serveur, certes tu ne connaîtras pas l'état du VPN en lui-même, mais au moins tu auras la disponibilité de ton serveur.

Bon, disons que ce serait un truc à implémenter éventuellement par la suite.
